language: php

services:
  - docker
  - mysql

addons:
  apt:
    packages:
      - postfix
      - libappindicator1
      - fonts-liberation

cache:
  directories:
    - $HOME/.npm

sudo: required
dist: trusty

env:
  global:
    - DOCKER_IMG=prestashop

matrix:
  fast_finish: true

before_script:
  - docker run --name=mysql -e MYSQL_ROOT_PASSWORD=doge -e MYSQL_DATABASE=prestashop -tid mysql
  - docker run --link mysql -e DB_SERVER=mysql -e DB_PASSWD=doge -e PS_INSTALL_AUTO=1 -e PS_COUNTRY=fr -e PS_DEV_MODE=0 -e PS_FOLDER_INSTALL=install-dev -e PS_FOLDER_ADMIN=admin-dev -e PS_HANDLE_DYNAMIC_DOMAIN=1 -p 80:80 -tid --name=prestashop prestashop/prestashop
  - docker exec prestashop rm -f /var/www/html/app/config/parameters.yml
  - docker exec prestashop pwd